### ISSUE TITLE
CREATE SUPER USER

### ISSUE THREAD

**Issue by ServicioIT** [ernestofgonzalez/djangorocket#36]
hola, estoy probando tu código, y he podido instalarlo sin problemas, pero:

1.  no puedo ejecutar createsuperuser para generar un administrador en django.
2. solo pude crear 1 usuario con el login, lo converti a admin en la base de datos y no me deja ingresar.
3. CSRF verification failed. Request aborted. sale constantemente cuando intento registrar uno nuevo.
4. la opcion de registro Google solo me salio 1 vez ya no volvio a salir (con las credenciales correctas)

espero tu respuesta, gracias

**Comment by ernestofgonzalez** [comment]
Hola @ServicioIT. Le echaré un vistazo a cada punto individualmente. 

Los iré documentando para futura referencia, si quieres dáme un par de horas y subo los fixes al `main` branch.

Empiezo:

> 1. no puedo ejecutar createsuperuser para generar un administrador en django.

Probé correr el command `createsuperuser` y obtuve

 ```
Traceback (most recent call last):
  File "/Users/ernestogonzalez/Documents/djangorocket/test_project/src/manage.py", line 22, in <module>
    main()
  File "/Users/ernestogonzalez/Documents/djangorocket/test_project/src/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/Users/ernestogonzalez/Documents/djangorocket/test_project/env/lib/python3.11/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/Users/ernestogonzalez/Documents/djangorocket/test_project/env/lib/python3.11/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/ernestogonzalez/Documents/djangorocket/test_project/env/lib/python3.11/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/ernestogonzalez/Documents/djangorocket/test_project/env/lib/python3.11/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 88, in execute
    return super().execute(*args, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ernestogonzalez/Documents/djangorocket/test_project/env/lib/python3.11/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ernestogonzalez/Documents/djangorocket/test_project/env/lib/python3.11/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 233, in handle
    self.UserModel._default_manager.db_manager(database).create_superuser(
TypeError: UserManager.create_superuser() missing 1 required positional argument: 'username'
```

**Comment by ernestofgonzalez** [comment]
> 2. solo pude crear 1 usuario con el login, lo converti a admin en la base de datos y no me deja ingresar.

Me puedes dar un poco más de contexto en este punto, @ServicioIT ?

**Comment by ServicioIT** [comment]
verifico y te cuento, es posible que todos los errores de creación de usuario estuvieran relacionados a este item

**Comment by ernestofgonzalez** [comment]
> verifico y te cuento, es posible que todos los errores de creación de usuario estuvieran relacionados a este item

El fix para `createsuperuser` lo acabo de subir a `main`. Confirma si soluciona los errores que te salían, por favor

**Comment by ServicioIT** [comment]
FUNCIONO PERFECTO, ya tengo acceso al admin y al home

![Screenshot 2023-06-06 at 4 48 02 PM](https://github.com/ernestofgonzalez/djangorocket/assets/102474250/a2ae9b56-9b46-4e12-b903-3fda0de3161a)

![Screenshot 2023-06-06 at 4 48 52 PM](https://github.com/ernestofgonzalez/djangorocket/assets/102474250/f5aa0a54-b6cf-4035-a34a-b7ca05b84dae)

**Comment by ServicioIT** [comment]
problema solucionado
