### ISSUE TITLE
Can't Set Up Postgres

### ISSUE THREAD

**Issue by TreavVasu** [ernestofgonzalez/djangorocket#45]
Hi @ernestofgonzalez 

I tried running docker-compose and was successful in it. But for migrations command I am not sure what to do.
I tried following these two solutions

- replaced postgres password by ALTER USER
   https://stackoverflow.com/questions/12720967/how-can-i-change-a-postgresql-user-password
- Added a user again named 'postgres' 
    - Also didn't work 
- I also cleared previous instances by 
`   docker-compose down --volumes  
`

- I know this may be an issue from my end but any help would be great
- Error:

````
PS D:\DEV\Repo\SAAS\djangorocket\TSaaS> python src/manage.py migrate                   
Traceback (most recent call last):
  File "C:\Users\write\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\backends\base\base.py", line 282, in ensure_connection
    self.connect()
  File "C:\Users\write\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Users\write\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\backends\base\base.py", line 263, in connect
    self.connection = self.get_new_connection(conn_params)
  File "C:\Users\write\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Users\write\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\backends\postgresql\base.py", line 215, in get_new_connection
    connection = Database.connect(**conn_params)
  File "C:\Users\write\AppData\Local\Programs\Python\Python39\lib\site-packages\psycopg2\__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (::1), port 5432 failed: FATAL:  password authentication failed for user "postgres"


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\DEV\Repo\SAAS\djangorocket\TSaaS\src\manage.py", line 22, in <module>
    main()
  File "D:\DEV\Repo\SAAS\djangorocket\TSaaS\src\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\write\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "C:\Users\write\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\write\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\write\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "C:\Users\write\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\base.py", line 96, in wrapped
    res = handle_func(*args, **kwargs)
  File "C:\Users\write\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\commands\migrate.py", line 114, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "C:\Users\write\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\migrations\executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "C:\Users\write\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\migrations\loader.py", line 58, in __init__
    self.build_graph()
  File "C:\Users\write\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\migrations\loader.py", line 235, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "C:\Users\write\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\migrations\recorder.py", line 81, in applied_migrations
    if self.has_table():
  File "C:\Users\write\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\migrations\recorder.py", line 57, in has_table
    with self.connection.cursor() as cursor:
  File "C:\Users\write\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Users\write\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\backends\base\base.py", line 323, in cursor
    return self._cursor()
  File "C:\Users\write\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\backends\base\base.py", line 299, in _cursor
    self.ensure_connection()
  File "C:\Users\write\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Users\write\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\backends\base\base.py", line 282, in ensure_connection
    self.connect()
  File "C:\Users\write\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\write\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\backends\base\base.py", line 282, in ensure_connection
    self.connect()
  File "C:\Users\write\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Users\write\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\backends\base\base.py", line 263, in connect
    self.connection = self.get_new_connection(conn_params)
  File "C:\Users\write\AppData\Local\Programs\Python\Python39\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Users\write\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\backends\postgresql\base.py", line 215, in get_new_connection   
    connection = Database.connect(**conn_params)
  File "C:\Users\write\AppData\Local\Programs\Python\Python39\lib\site-packages\psycopg2\__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: connection to server at "localhost" (::1), port 5432 failed: FATAL:  password authentication failed for user "postgres"
``` `

**Comment by ernestofgonzalez** [comment]
Hi, @TreavVasu. Sorry for taking a while to get back to you I've been busy with other projects.

It seems there is a mismatch between the passwords provided to
- the PostgreSQL container upon creation and
- the Django settings file.

I tried playing around a bit and this happens anytime I
1. Generate the project using Django Rocket
2. Run `docker-compose up`
3. Change the passwords in either `DATABASE_URL` or `POSTGRES_PASSWORD`

The problem lies in step 3. Changing the passwords in your `.env` file do not change the password in the already existing `postgres` user. I'm not sure if it is possible to alter `postgres` user password (without knowing the current password) since it is a superuser.

Even when you delete all volumes, containers, networks opened by Docker, there is still a lot of "unused" data that goes undeleted, and I fear that this includes your existing `postgres` superuser. I haven't figured how to completely erase it yet.

My advice is update your `.env` file so the passwords match and start with a new container, simply by renaming it in your `docker-compose.yml` file like so 

```yml
version: "3.1"

services:

  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"

  redis:
    image: bitnami/redis:latest
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
```
